
```{r include=FALSE, warning=FALSE, message=FALSE}
# Stop the R code from displaying, stop warnings and messages from displaying
# Set the resolution and size of plots
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dpi = 320, out.width = "100%")

# Source Animal Services data
# Note that this also loads packages
source("scripts/processing.R")

# Set base theme for plots
theme_set(theme_minimal() +
            theme(text = element_text(family = "Segoe UI"),
                  axis.title = element_blank(),
                  panel.grid.major = element_line(color = "black", linetype = "dotted"),
                  panel.background = element_blank()))
```

# Summerfield {#summerfield}

## Monthly call volume {#summerfieldvolume}

How many calls do we receive each month?

```{r}
call_data %>%
  filter(jurisdiction == "Summerfield") %>%
  filter(common_calltime >= (floor_date(Sys.Date() - 365, unit = "1 month"))) %>%
  group_by(common_calltime) %>%
  summarise(total = n()) %>%
  ungroup() %>%
  ggplot(aes(common_calltime, total)) +
  geom_col(fill = "#1d4c94") +
  geom_text(aes(label = scales::comma(total)), color = "white", nudge_y = -1) +
  scale_y_continuous(labels = scales::comma_format())
```

## Nature Breakdown {#summerfieldnatures}

What are the top 10 nature codes assigned to calls.

```{r}
call_data %>%
  filter(jurisdiction == "Summerfield") %>%
  filter(common_calltime >= (floor_date(Sys.Date() - 365, unit = "1 month"))) %>%
  filter(nature != "Transport To Animal Shelter") %>%
  group_by(nature) %>%
  summarise(total = n()) %>%
  ungroup() %>%
  arrange(desc(total)) %>%
  top_n(10, total) %>%
  ggplot(aes(reorder(nature, total), total)) +
  geom_col(fill = "#1d4c94") +
  geom_text(aes(label = scales::comma(total)), color = "white", nudge_y = -1) +
  scale_y_continuous(labels = scales::comma_format()) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 10))
```

# Location Overview {#summerfieldlocation}

This is a map showing the call counts for hexagonal bins. The darker the color, the more calls we received in that area.

```{r}
for_map <- call_dat_sf %>%
  filter(jurisdiction == "Summerfield") %>%
  filter(nature != "Transport To Animal Shelter") %>%
  filter(common_calltime >= (floor_date(Sys.Date() - 365, unit = "1 month")))

call_dat_sf %>%
  filter(jurisdiction == "Summerfield") %>%
  filter(nature != "Transport To Animal Shelter") %>%
  filter(common_calltime >= (floor_date(Sys.Date() - 365, unit = "1 month"))) %>%
  ggplot() +
  geom_sf(data = filter(guil_places, NAME == "Summerfield"), color = "grey", fill = NA) +
  geom_text(data = filter(places_labels, NAME == "Summerfield"), aes(long, lat, label = NAME), color = "black", size = 3) +
  geom_hex(data = data.frame(st_coordinates(for_map)), aes(X, Y), alpha = 0.4, show.legend = FALSE) +
  scale_fill_viridis_c(option = "magma", direction = -1)
```

